language: ruby
rvm:
  - "2.1.2"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:test:prepare #rake db:test:prepare
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres