sudo: required
language: ruby
rvm:
- 2.2.0
env:
  global:
  - WEB_APP_URL: 'http://localhost:9000/#/social'
  - secure: FT+jBK9RINVbBr9IZs71AV8hterXE6ANSvoU5sDvxwXdfaGOaaYnbVR4hdV4oLE2kQG+byqpLwsKshIg8CygQcSaAUVn8Gp7qeMtCCP9d8uGnRqSJMHcndyoBWPhz/bfLsDEmZSaE6HXLekxU35eQJRUQGp6Ztoji/g/8itLTyo=
  - secure: ZsZ8wkKJ68/l2C0AJcR8p6NYhs2un7mXUU45RTEbmK/68qICficSdpVJKVvyh/nhvYFDtwurOWSsS0EjFZ7kIgnio0kyBx3GddDZqrWsuGVQVIv+md7SdcGiH/zKvlY/WhRuO958e0A0abBiLJo8OmDhpvE9BrhkvNTYB1F3zm8=
  - secure: gwyCZo/UYLWSPMI051RatTemRc0JV0PtdY0VHDY92K6+pbMDosxdZsvo3Gh4+S8TEvWCEYvH3s2kFe1OSxBSEFrVEtRjmI6bLDCAGCmLaQUFy/gBg+F34NiPUVLVvEIVjH/CwLd5i+nWxuHgRqxdeA7OpB1uDC5rabv7wTCATVk=
  - secure: Wv/vYqD1QrZ3iy36wuP7NPF1arzGfvbQfZQXE7TSxCkps3AMTJDH31W0JZVo8xDsbWxuoID2rjhCwfU03z12lfpo73BJODZdowg7jrGSzD8ZrjBLDMGDiteKZrwp7mmgWDkx3cHPRanAsgFDTVb7u2oUj/CKxEVvHNSo87tYd4Y=
  - secure: CD7XLDrOX5LK7UDdzjxoNXPoYOXi99ZZ637t4ubfAdGRNeiP7wtbCaxdhOl0pXSRsXozp7YVFTyVkcRDY9CenWGtsN7lWSVraNCNOrip39jo4dLJPJk+TpupzyDaSx9plhGLIlcYY1N6Czh+dl5gsOgOAWiXEUAUnSHUKNwK+r8=
  - secure: boulW5lHc1HqlF6mLXTfilNEBFb693UFUst8HpD3bwfH5pJWDexrcef3p7NgU90oJnUwbjH5sAk3fJ2OamLezRJcbA0jFEnZo1fwwtfcAJtzDu5hzQO5tsbBVJksLY1hjM/VNjvz0FxnptcA2OYAt0ESNbPp0QcyiyG3R5Sgdtw=
services:
  - mysql
script:
- CODECLIMATE_REPO_TOKEN=16d109f017a77e12e9af52396b903a991307530a27c1922ded94cfc0757a137a
  bundle exec rake
- RAILS_ENV=test bundle exec rake --trace db:schema:load
- bundle exec rspec spec
before_script:
- cp config/database.yml.travis config/database.yml
- mysql -e 'CREATE DATABASE travis_ci_test;'
deploy:
  provider: heroku
  app: gatorapi
  api_key:
    secure: el+UQKgjSj7/l5cg5fjRR59FDp5Ba3FUqQK/TLpw8EWSG0Ukk3sbwLWx4NSLfVY16DwpSfV2vBYxzU29zJD13W5FU6XrIbynFs3tkYzUZAth4wl/0MqTe2efdkV2tmp6Jp6mX3hv2Y6Vp1urlq56+KoM/wY/QfF+wokHCBa+v+s=
  run:
  - rake db:migrate
  - rake db:seed
  - restart
  - rake cleanup
